README.md

Since #10 was closed, I thought it best to clarify this.

Add uniqueness constraint to README.md

---

README.md
exercises/csharp-1-a/.meta/test_messages.json
exercises/csharp-1-b/.meta/test_messages.json
exercises/csharp-2-a/.meta/test_messages.json
exercises/csharp-2-b/.meta/test_messages.json

@iHiD Let me know what you think.

csharp: add test messages for test results

---

README.md

The PR is self-documenting. #22 shows a sample implementation.

Add information about the addition of a config.json

---

exercises/python-1-a/.meta/config.json

@yawpitch, @cmccandless: You'll want to flesh this out but I'm just putting something in place for so you can start testing the test-runner.
(cc @ccare)

Add config for python-1-a

---

exercises/x86-64-assembly-1-a/README.md

x86-64-assembly/a: Update README for part 1

---

exercises/x86-64-assembly-1-b/README.md

x86-64-assembly/b: Update README for part 1

---

exercises/x86-64-assembly-2-a/README.md

x86-64-assembly/a: Update README for part 2

---

exercises/elm-1-a/.meta/Example.Dict.2.elm
exercises/elm-1-a/.meta/Example.Dict.elm
exercises/elm-1-a/.meta/Example.List.2.elm
exercises/elm-1-a/.meta/Example.List.3.elm
exercises/elm-1-a/.meta/Example.List.elm
exercises/elm-1-a/.meta/config.json
exercises/elm-1-a/README.md
exercises/elm-2-a/.meta/Example.Dict.elm
exercises/elm-2-a/.meta/Example.List.elm
exercises/elm-2-a/.meta/Start.Dict.2.elm
exercises/elm-2-a/.meta/Start.Dict.elm
exercises/elm-2-a/.meta/Start.List.2.elm
exercises/elm-2-a/.meta/Start.List.3.elm
exercises/elm-2-a/.meta/Start.List.elm
exercises/elm-2-a/.meta/config.json
exercises/elm-2-a/README.md
exercises/elm-2-a/elm.json
exercises/elm-2-a/src/AggregateScorers.elm
exercises/elm-2-a/tests/Tests.elm

Hi There
This is Elm exercise A, part 1.
This should take an experienced Elm programmer around 10-15  minutes.
I think there is some potential to add some help to the readme to make it easier / quicker, without guiding the user to a solution. I had to look up String.fromInt for example, which took time, and is basically incidental to the exercise.
This pull request also adds a missing configuration for a test for part 1 a

Add elm-2-a

---

README.md

PR in attempt to clarify descriptions of test messages, for
https://github.com/exercism/research_experiment_1/issues/32

Added additional test message example

---

exercises/elm-1-b/.meta/Example.Parser.elm
exercises/elm-1-b/.meta/Example.String.elm
exercises/elm-1-b/.meta/config.json
exercises/elm-1-b/README.md
exercises/elm-1-b/elm.json
exercises/elm-1-b/src/Pizza.elm
exercises/elm-1-b/tests/Tests.elm

While the exercise A was a data manipulation problem (lists, dicts, etc.) this one is a parsing problem, aiming at turning a string into a list of structured data (a `List Pizza`). It should take 10 to 15 minutes to an Elm dev.
I have ideas on how to increase the difficulty for the second part, for example adding ingredients of pizzas, which are in an unknown number for each pizza when calling the parsing function.

Add first part of Elm exercise b

---

config.json

@ErikSchierboom - We need to remember to do this. Could you check the file is a correct representation of the current state tomorrow pls.

Add Elm and Go exercises

---

exercises/go-1-b/go_1_b_test.go
exercises/go-2-a/go_2_a_test.go
exercises/go-2-b/go_2_b_test.go

[Go] Improve error output to new format

---

exercises/csharp-1-a/README.md
exercises/csharp-1-b/README.md
exercises/csharp-2-a/README.md
exercises/csharp-2-b/README.md
exercises/elm-1-a/README.md
exercises/elm-1-b/README.md
exercises/elm-2-a/README.md
exercises/go-1-a/README.md
exercises/go-1-b/README.md
exercises/go-2-a/README.md
exercises/go-2-b/README.md
exercises/javascript-1-a/README.md
exercises/python-1-a/README.md
exercises/python-1-b/README.md
exercises/ruby-1-a/README.md
exercises/ruby-1-b/README.md
exercises/rust-1-a/README.md
exercises/rust-1-b/README.md
exercises/rust-2-a/README.md
exercises/rust-2-b/README.md
exercises/x86-64-assembly-1-a/README.md
exercises/x86-64-assembly-1-b/README.md
exercises/x86-64-assembly-2-a/README.md
exercises/x86-64-assembly-2-b/README.md

We were saying:
> This exercise should take 10-15 minutes.
In order to not make people feel stupid, we should clarify that this
expectation assumes that you're proficient with the language:
> This exercise should take 10-15 minutes for a programmer who is
proficient in LANGUAGE.
Closes https://github.com/exercism/research_experiment_1/issues/70

Clarify expectations around time vs proficiency

---

exercises/ruby-1-a/README.md
exercises/ruby-1-a/ruby_1_a_test.rb

I played with the Ruby 1 a exercise, and I really like it. It seems like it has a really good scope and level of complexity.
There were a few things that were unclear as I was working through it:
- the SKU should be a Symbol rather than a String. This was not
specified, and the example showed a constant, which doesn't tell the
research subject what the type is.
- the price list shows a combination of integers and floats. The
instructions state that the total amount should have 2 decimal places,
but the example shows a return value of an integer with no decimal
places.
- the example shows the item names in lowercase, whereas the actual
table shows the names capitalized.
- the README doesn't specify that the `item_list` requires the names
to be unique.
I also updated the tests to assert …

ruby: Ensure instructions are complete for ruby-1-a

---

exercises/elm-1-a/README.md
exercises/elm-1-b/README.md
exercises/elm-2-a/README.md

This PR is both for consistency purposes and for gained insights, where we are targeting people that are familiar with the language.

[Elm] Remove documentation reference from README

---

config/maintainers.json

Replaces https://github.com/exercism/research_experiment_1/pull/107
cc @tehsphinx

Add go/research-exercise for tehsphinx

---

exercises/ruby-2-a/.meta/config.json
exercises/ruby-2-a/.meta/start/1/ruby_2_a.rb
exercises/ruby-2-a/.meta/start/2/ruby_2_a.rb
exercises/ruby-2-a/.meta/start/3/ruby_2_a.rb
exercises/ruby-2-a/README.md
exercises/ruby-2-a/ruby_2_a.rb
exercises/ruby-2-a/ruby_2_a_example.rb
exercises/ruby-2-a/ruby_2_a_test.rb

I've been doing some work on the extension for the shopping cart exercise and I'd like to get some feedback before continuing. 
As you can see I added the `scan_coupon` method and two types of discounts `half price` and `fix`. What do you think about the scope and level of complexity?  As you can see, I already have three more tests in mind that will increase the scope and complexity but I'm not sure where we want to stop.
Any other suggestions will be more than welcome, thanks!

[Ruby] Extension for the shopping cart exercise

---

config/maintainers.json

Elm contributions already present.
Rust contribution to test runner incoming (https://github.com/exercism/rust-test-runner/pull/11)

Add mpizenberg as maintainer

---

exercises/elm-1-b/README.md
exercises/elm-2-b/README.md

I've tried to make the instructions a little bit clearer

[Elm] Update instructions

---

exercises/elm-1-b/.meta/config.json
exercises/elm-1-b/tests/Tests.elm
exercises/elm-2-b/.meta/config.json
exercises/elm-2-b/tests/Tests.elm

I'm adding more tests to ensure people can't hard-code the results.

[Elm] Add more tests

---

exercises/csharp-1-a/README.md
exercises/csharp-1-b/README.md
exercises/csharp-2-a/README.md
exercises/csharp-2-b/README.md
exercises/elm-1-a/README.md
exercises/elm-1-b/README.md
exercises/elm-2-a/README.md
exercises/elm-2-b/README.md
exercises/go-1-a/README.md
exercises/go-1-b/README.md
exercises/go-2-a/README.md
exercises/go-2-b/README.md
exercises/javascript-1-a/README.md
exercises/javascript-2-a/README.md
exercises/python-1-a/README.md
exercises/python-1-b/README.md
exercises/python-2-a/README.md
exercises/python-2-b/README.md
exercises/ruby-1-a/README.md
exercises/ruby-1-b/README.md
exercises/ruby-2-a/README.md
exercises/rust-1-a/README.md
exercises/rust-1-b/README.md
exercises/rust-2-a/README.md
exercises/rust-2-b/README.md
exercises/x86-64-assembly-1-a/README.md
exercises/x86-64-assembly-1-b/README.md
exercises/x86-64-assembly-2-a/README.md
exercises/x86-64-assembly-2-b/README.md

[Docs] Normalize introduction

---

exercises/ruby-1-b/README.md
exercises/ruby-1-b/ruby_1_b.rb

Each commit has a description.

Final tweaks

---

exercises/common-lisp-1-a/.meta/example-3.lisp

This one just missed that last merge, but this brings our number of examples up to par!

[Common Lisp] Add a third example file

---

exercises/rust-1-a/README.md

As per #146, I've tried to make the instructions a bit more clear on what is expected of the user. To do so, I've used the way the problem is phrased in `rust-2-a`.
Closes #146

[Rust] Update increment instructions

---

exercises/go-1-a/README.md
exercises/go-2-a/README.md

Fix invalid example in the Go 1-a and 2-a exercises.

[Go] Fix instructions

---

exercises/python-1-b/README.md

added missing end of the quotation mark

fixed README.md typo
